version: '2'
services:
    elasticsearch:
        image: khezen/elasticsearch:5
        environment:
            HOSTS: '[127.0.0.1]'
            HEAP_SIZE: 1g
            ELASTIC_PWD: changeme
            KIBANA_PWD: changeme
            LOGSTASH_PWD: changeme
            BEATS_PWD: changeme
            CA_PWD: changeme
            KS_PWD: changeme
            TS_PWD: changeme
        volumes:
            - es_data:/usr/share/elasticsearch/data
            - es_config:/usr/share/elasticsearch/config           
        ports:
             - "9200:9200"
             - "9300:9300"
        networks:
            - elk
        restart: unless-stopped

    kibana:
        links:
            - elasticsearch
        image: khezen/kibana:5
        environment:
            KIBANA_PWD: changeme
            ELASTICSEARCH_HOST: elasticsearch
            ELASTICSEARCH_PORT: 9200
        volumes:
            - kibana_config:/etc/kibana
            - es_config:/etc/elasticsearch/
        ports:
             - "5601:5601"
        networks:
            - elk
        restart: unless-stopped

    logstash:
        links:
            - elasticsearch
        image: khezen/logstash:5
        environment:
            HEAP_SIZE: 1g
            LOGSTASH_PWD: changeme
            ELASTICSEARCH_HOST: elasticsearch
            ELASTICSEARCH_PORT: 9200
            TS_PWD: changeme
        volumes:
            - logstash_config:/etc/logstash/conf.d
            - es_config:/etc/elasticsearch/
        ports:
             - "5000:5000"
             - "5001:5001/udp"
        networks:
            - elk
        restart: unless-stopped
    
    elastalert:
        links:
            - elasticsearch
        image: khezen/elastalert:support_es5
        environment:
            ELASTALERT_USER: elastalert
            ELASTALERT_PWD: changeme
            ELASTICSEARCH_HOST: elasticsearch
            ELASTICSEARCH_PORT: 9200
        volumes:
            - elastalert_config:/etc/elastalert
            - elastalert_rules:/usr/share/elastalert/rules
        networks:
            - elk
        restart: unless-stopped

volumes:
  certificates:
    driver: local
  es_config:
    driver: local
  es_data:
    driver: local
  kibana_config:
    driver: local
  logstash_config:
    driver: local
  elastalert_config:
    driver: local
  elastalert_rules:
    driver: local

networks:
  elk:
    driver: bridge