version: '2'
services:    
    elastalert:
        external_links:
            - dockerelk_elasticsearch1:elasticsearch
        image: khezen/elastalert:support_es5
        environment:
            ELASTALERT_USER: elastalert
            ELASTALERT_PWD: changeme
            ELASTICSEARCH_HOST: elasticsearch
            ELASTICSEARCH_PORT: 9200
        volumes:
            - /etc/elastalert:/etc/elastalert
            - /usr/share/elastalert/rules:/usr/share/elastalert/rules
        networks:
            - elk
        restart: unless-stopped

networks:
    elk:
        external:
            name: dockerelk_elk