version: '2'
services:    
    httpbeat:
        external_links:
            - dockerelk_elasticsearch1:elasticsearch
        image: khezen/httpbeat
        environment:
            HTTPBEAT_USER: beats
            HTTPBEAT_PWD: changeme
            ELASTICSEARCH_HOST: elasticsearch
            ELASTICSEARCH_PORT: 9200
        volumes:
            - /etc/httpbeat:/etc/httpbeat
        networks:
            - elk
        restart: unless-stopped

networks:
    elk:
        external:
            name: dockerelk_elk